
title: John Doe
description: Curriculum Vita
keywords: John Doe, Curriculum Vitæ, CV, Professor, Example
url: https://ssgberk.github.io/professor-website-exemple
repository: https://github.com/ssgberk/professor-website-exemple
timezone: UTC

author: matbrgz
author_url: https://github.com/matbrgz
organization: matbrgz
organization_url: https://matbrgz.com

contact: john.doe[at]example[dot]com
github: https://github.com/ssgberk/professor-website-exemple

image: /images/avatar.jpg

languages: ["en", "pt-br", "es"]

collections:
  articles:
    output: true

jekyll_get:
  data: team
  json: 'https://18f.gsa.gov/hub/api/team/'

plugins:
- jekyll-giphy
- jekyll-multiple-languages-plugin
- jekyll-seo-tag
- jekyll-target-blank
- jemoji
- premonition

mermaid:
  src: '_assets/js/mermaid.min.js'

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- archive
- Gemfile
- Gemfile.lock
- script
- vendor